### ISSUE TITLE
[BUG] - Black Import Error in Tests

### ISSUE THREAD

**Issue by Adam-D-Lewis** [Quansight/qhub#1251]
Black seems to be out of date causing CI tests to fail.  You can see this from https://github.com/Quansight/qhub/runs/6039400018?check_suite_focus=true.  

```
Run black --version
  black --version
  black qhub --diff
  black --check qhub
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.1[2](https://github.com/Quansight/qhub/runs/6039400018?check_suite_focus=true#step:5:2)/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/[3](https://github.com/Quansight/qhub/runs/6039400018?check_suite_focus=true#step:5:3).8.12/x6[4](https://github.com/Quansight/qhub/runs/6039400018?check_suite_focus=true#step:5:4)/lib
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/black/__init__.py", line 6606, in patched_main
    patch_click()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/black/__init__.py", line 6[5](https://github.com/Quansight/qhub/runs/6039400018?check_suite_focus=true#step:5:5)95, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/opt/hostedtoolcache/Python/3.8.12/x[6](https://github.com/Quansight/qhub/runs/6039400018?check_suite_focus=true#step:5:6)4/lib/python3.[8](https://github.com/Quansight/qhub/runs/6039400018?check_suite_focus=true#step:5:8)/site-packages/click/__init__.py)
Error: Process completed with exit code 1.
```

The fix seems to be upgrading to black==22.3.0 (https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click)

**Comment by Adam-D-Lewis** [comment]
Seems to already be fixed on main
