### ISSUE TITLE
[BUG] VScode extension terminal is not loading

### ISSUE THREAD

**Issue by viniciusdc** [Quansight/qhub#1369]
After #1360 was introduced, we lost the ability to use the inbuilt terminal from within the VScode extension. 

This is the current status of the terminal when we attempt to load it:

![image](https://user-images.githubusercontent.com/51954708/178524005-7281ca2d-105b-4f19-8d9a-8617e7903ea4.png)

and this is the extension manager logs:
```
[2022-07-12 12:13:24.491] [window] [error] [object Event]: Error: [object Event]
    at Object.E [as ensureError] (https://quansight-beta.qhub.dev/user/vcerutti@quansight.com/vscode/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/loader.js:3:4182)
    at i._createLoadError (https://quansight-beta.qhub.dev/user/vcerutti@quansight.com/vscode/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/loader.js:5:8131)
    at i._onLoadError (https://quansight-beta.qhub.dev/user/vcerutti@quansight.com/vscode/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/loader.js:5:8250)
    at f (https://quansight-beta.qhub.dev/user/vcerutti@quansight.com/vscode/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/loader.js:5:10089)
    at Object.errorback (https://quansight-beta.qhub.dev/user/vcerutti@quansight.com/vscode/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/loader.js:5:10445)
    at e.triggerErrorback (https://quansight-beta.qhub.dev/user/vcerutti@quansight.com/vscode/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/loader.js:3:11144)
    at https://quansight-beta.qhub.dev/user/vcerutti@quansight.com/vscode/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/loader.js:3:10850
    at HTMLScriptElement.f (https://quansight-beta.qhub.dev/user/vcerutti@quansight.com/vscode/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/loader.js:3:11365)
```

Logs from DevTools:
![image](https://user-images.githubusercontent.com/51954708/178525558-f8a3014f-c8d7-4c5c-9b43-87de6b70e898.png)

**Comment by viniciusdc** [comment]
Worth checking https://github.com/microsoft/vscode/issues/69665#issue-416235055

**Comment by viniciusdc** [comment]
This docs might be useful for debugging strategies https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch

**Comment by kcpevey** [comment]
This has been resolved. Thanks guys! 

Related: https://github.com/Quansight/qhub/pull/1383 and https://github.com/nebari-dev/nebari-docker-images/pull/14
