### ISSUE TITLE
[BUG] - Flake8 failing - upstream issue

### ISSUE THREAD

**Issue by iameskild** [Quansight/qhub#1483]
### OS system and architecture in which you are running QHub

GitHub Actions - ubuntu linux

### Expected behavior

Flake8 failing.

### Actual behavior

Flake8 to not fail.

### How to Reproduce the problem?

```
$ Run flake8 --version
```

### Command output

```bash session
$ Run flake8 --version
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.14/x64/bin/flake[8](https://github.com/Quansight/qhub/actions/runs/3136226763/jobs/5092868539#step:6:9)", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/opt/hostedtoolcache/Python/3.7.[14](https://github.com/Quansight/qhub/actions/runs/3136226763/jobs/5092868539#step:6:15)/x64/lib/python3.7/site-packages/flake8/main/application.py", line 350, in _run
    self.initialize(argv)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/main/application.py", line 330, in initialize
    self.find_plugins(config_finder)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/main/application.py", line [15](https://github.com/Quansight/qhub/actions/runs/3136226763/jobs/5092868539#step:6:16)3, in find_plugins
    self.check_plugins = plugin_manager.Checkers(local_plugins.extension)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/plugins/manager.py", line 357, in __init__
    self.namespace, local_plugins=local_plugins
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/plugins/manager.py", line [23](https://github.com/Quansight/qhub/actions/runs/3136226763/jobs/5092868539#step:6:24)8, in __init__
    self._load_entrypoint_plugins()
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/flake8/plugins/manager.py", line [25](https://github.com/Quansight/qhub/actions/runs/3136226763/jobs/5092868539#step:6:26)4, in _load_entrypoint_plugins
    eps = importlib_metadata.entry_points().get(self.namespace, ())
AttributeError: 'EntryPoints' object has no attribute 'get'
Error: Process completed with exit code 1.
```

### Anything else?

It seems this is the result of Flake8 pinning `importlib-metadata`: https://github.com/PyCQA/flake8/issues/1522

I fear, for now, that we will also likely have to pin `importlib-metadata`.

**Comment by iameskild** [comment]
fixed by https://github.com/Quansight/qhub/pull/1358
