### ISSUE TITLE
qhub command line should display user-friendly errors

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub#475]
In places, the `qhub` command raises an exception when knowingly handling an error. For example:

```
 ➜ qhub render -c test.yaml
Traceback (most recent call last):
  File "/Users/dan/.virtualenvs/qhub-cloud/bin/qhub", line 33, in <module>
    sys.exit(load_entry_point('qhub', 'console_scripts', 'qhub')())
  File "/Users/dan/Dev/qhub-cloud/qhub/__main__.py", line 7, in main
    cli(sys.argv[1:])
  File "/Users/dan/Dev/qhub-cloud/qhub/cli/__init__.py", line 40, in cli
    args.func(args)
  File "/Users/dan/Dev/qhub-cloud/qhub/cli/render.py", line 19, in handle_render
    raise ValueError(
ValueError: passed in configuration filename=test.yaml must exist
```

It should really catch and display the error message without showing the stack trace.

**Comment by costrouc** [comment]
Totally agree. I've seen similar issues with the errors the pydantic is throwing on validation errors. This would be a great area for development
