### ISSUE TITLE
Test config file for DO has validation errors

### ISSUE THREAD

**Issue by aktech** [Quansight/qhub#55]
```
Traceback (most recent call last):
  File "/Users/aktech/anaconda3/envs/qhub-jupytercon/bin/qhub", line 8, in <module>
    sys.exit(main())
  File "/Users/aktech/anaconda3/envs/qhub-jupytercon/lib/python3.8/site-packages/qhub/__main__.py", line 7, in main
    cli(sys.argv[1:])
  File "/Users/aktech/anaconda3/envs/qhub-jupytercon/lib/python3.8/site-packages/qhub/cli/__init__.py", line 36, in cli
    args.func(args)
  File "/Users/aktech/anaconda3/envs/qhub-jupytercon/lib/python3.8/site-packages/qhub/cli/render.py", line 29, in handle_render
    verify(config)
  File "/Users/aktech/anaconda3/envs/qhub-jupytercon/lib/python3.8/site-packages/qhub/schema.py", line 196, in verify
    Main(**config)
  File "pydantic/main.py", line 346, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 4 validation errors for Main
profiles -> jupyterlab -> 0 -> kubespawner_override -> cpu_guarentee
  field required (type=value_error.missing)
profiles -> jupyterlab -> 0 -> kubespawner_override -> mem_guarentee
  field required (type=value_error.missing)
profiles -> jupyterlab -> 1 -> kubespawner_override -> cpu_guarentee
  field required (type=value_error.missing)
profiles -> jupyterlab -> 1 -> kubespawner_override -> mem_guarentee
  field required (type=value_error.missing)
```

After fixing the above via:

```diff
diff --git a/tests/assets/config_do.yaml b/tests/assets/config_do.yaml
index 7573804..d5f8f00 100644
--- a/tests/assets/config_do.yaml
+++ b/tests/assets/config_do.yaml
@@ -76,18 +76,18 @@ profiles:
         - admin
       kubespawner_override:
         cpu_limit: 1
-        cpu_guarantee: 1
+        cpu_guarentee: 1
         mem_limit: 1G
-        mem_guarantee: 1G
+        mem_guarentee: 1G
         image: "quansight/qhub-jupyterlab:4c8c28332be1fde32f786c54a5961b5f3d789e16"
     - display_name: Medium Instance
       description: Stable environment with 1.5 cpu / 2 GB ram
       default: true
       kubespawner_override:
         cpu_limit: 1.5
-        cpu_guarantee: 1.25
+        cpu_guarentee: 1.25
         mem_limit: 2G
-        mem_guarantee: 2G
+        mem_guarentee: 2G
         image: "quansight/qhub-jupyterlab:4c8c28332be1fde32f786c54a5961b5f3d789e16"

   dask_worker:
```

I see another error:

```
Traceback (most recent call last):
  File "/Users/aktech/anaconda3/envs/qhub-jupytercon/lib/python3.8/site-packages/cookiecutter/generate.py", line 352, in generate_files
    generate_file(
  File "/Users/aktech/anaconda3/envs/qhub-jupytercon/lib/python3.8/site-packages/cookiecutter/generate.py", line 175, in generate_file
    rendered_file = tmpl.render(**context)
  File "/Users/aktech/anaconda3/envs/qhub-jupytercon/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/aktech/anaconda3/envs/qhub-jupytercon/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/aktech/anaconda3/envs/qhub-jupytercon/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "./infrastructure/kubernetes.tf", line 39, in top-level template code
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'shared_filesytem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aktech/anaconda3/envs/qhub-jupytercon/bin/qhub", line 8, in <module>
    sys.exit(main())
  File "/Users/aktech/anaconda3/envs/qhub-jupytercon/lib/python3.8/site-packages/qhub/__main__.py", line 7, in main
    cli(sys.argv[1:])
  File "/Users/aktech/anaconda3/envs/qhub-jupytercon/lib/python3.8/site-packages/qhub/cli/__init__.py", line 36, in cli
    args.func(args)
  File "/Users/aktech/anaconda3/envs/qhub-jupytercon/lib/python3.8/site-packages/qhub/cli/render.py", line 32, in handle_render
    render_default_template(args.output, args.config, force=args.force)
  File "/Users/aktech/anaconda3/envs/qhub-jupytercon/lib/python3.8/site-packages/qhub/render/__init__.py", line 74, in render_default_template
    render_template(input_directory, output_directory, config_filename, force=force)
  File "/Users/aktech/anaconda3/envs/qhub-jupytercon/lib/python3.8/site-packages/qhub/render/__init__.py", line 109, in render_template
    generate_files(
  File "/Users/aktech/anaconda3/envs/qhub-jupytercon/lib/python3.8/site-packages/cookiecutter/generate.py", line 359, in generate_files
    raise UndefinedVariableInTemplate(msg, err, context)
cookiecutter.exceptions.UndefinedVariableInTemplate: Unable to create file 'infrastructure/kubernetes.tf'. Error message: 'dict object' has no attribute 'shared_filesytem'. Context: {'cookiecutter': ChainMap({'project_name': 'do-jupyterhub', 'provider': 'do', 'ci_cd': 'github-actions', 'domain': 'do.qhub.dev', 'security': {'authentication': {'type': 'GitHub', 'config': {'client_id': 'CLIENT_ID', 'client_secret': 'CLIENT_SECRET', 'oauth_callback_url': 'https://jupyter.do.qhub.dev/hub/oauth_callback'}}, 'users': {'costrouc': {'uid': 1000, 'primary_group': 'users', 'secondary_groups': ['billing']}, 'dharhas': {'uid': 1001, 'primary_group': 'admin'}, 'tonyfast': {'uid': 1002, 'primary_group': 'admin'}, 'prasunanand': {'uid': 1003, 'primary_group': 'admin'}, 'aktech': {'uid': 1004, 'primary_group': 'users', 'secondary_groups': ['admin']}}, 'groups': {'users': {'gid': 100}, 'admin': {'gid': 101}, 'billing': {'gid': 102}}}, 'digital_ocean': {'region': 'nyc3', 'kubernetes_version': '1.16.6-do.2', 'node_groups': {'general': {'instance': 's-2vcpu-4gb', 'min_nodes': 1, 'max_nodes': 1}, 'user': {'instance': 's-2vcpu-4gb', 'min_nodes': 1, 'max_nodes': 4}, 'worker': {'instance': 's-2vcpu-4gb', 'min_nodes': 1, 'max_nodes': 4}}}, 'default_images': {'jupyterhub': 'quansight/qhub-jupyterhub:4c8c28332be1fde32f786c54a5961b5f3d789e16', 'jupyterlab': 'quansight/qhub-jupyterlab:4c8c28332be1fde32f786c54a5961b5f3d789e16', 'dask_worker': 'quansight/qhub-dask-worker:4c8c28332be1fde32f786c54a5961b5f3d789e16'}, 'storage': {'conda_store': '20Gi', 'shared_filesystem': '10Gi'}, 'profiles': {'jupyterlab': [{'display_name': 'Small Instance', 'description': 'Stable environment with 1 cpu / 1 GB ram', 'groups': ['admin'], 'kubespawner_override': {'cpu_limit': 1, 'cpu_guarentee': 1, 'mem_limit': '1G', 'mem_guarentee': '1G', 'image': 'quansight/qhub-jupyterlab:4c8c28332be1fde32f786c54a5961b5f3d789e16'}}, {'display_name': 'Medium Instance', 'description': 'Stable environment with 1.5 cpu / 2 GB ram', 'default': True, 'kubespawner_override': {'cpu_limit': 1.5, 'cpu_guarentee': 1.25, 'mem_limit': '2G', 'mem_guarentee': '2G', 'image': 'quansight/qhub-jupyterlab:4c8c28332be1fde32f786c54a5961b5f3d789e16'}}], 'dask_worker': {'Small Worker': {'worker_cores_limit': 1, 'worker_cores': 1, 'worker_memory_limit': '1G', 'worker_memory': '1G', 'image': 'quansight/qhub-dask-worker:4c8c28332be1fde32f786c54a5961b5f3d789e16'}, 'Medium Worker': {'worker_cores_limit': 1.5, 'worker_cores': 1.25, 'worker_memory_limit': '2G', 'worker_memory': '2G', 'image': 'quansight/qhub-dask-worker:4c8c28332be1fde32f786c54a5961b5f3d789e16'}}}, 'environments': {'environment-default.yaml': {'name': 'default', 'channels': ['conda-forge', 'defaults'], 'dependencies': ['python=3.7', 'ipykernel', 'ipywidgets', 'dask==2.14.0', 'distributed==2.14.0', 'dask-gateway=0.6.1', 'numpy', 'numba', 'pandas']}, 'environment-example-2.yaml': {'name': 'example-2', 'channels': ['conda-forge', 'defaults'], 'dependencies': ['python=3.7', 'ipykernel', 'ipywidgets', 'dask==2.14.0', 'distributed==2.14.0', 'dask-gateway=0.6.1', 'numpy', 'numba', 'pandas', 'jinja2', 'pyyaml']}}, 'repo_directory': 'qhub-jupytercon-demo'}, {'repo_directory': None, 'project_name': None, 'provider': None, 'ci_cd': None, 'endpoint': None, 'security': None, 'default_images': None, 'profiles': None, 'environments': None, 'storage': None, 'digital_ocean': {'region': None, 'kubernetes_version': None, 'node_groups': {'general': {'instance': None, 'min_nodes': None, 'max_nodes': None}, 'user': {'instance': None, 'min_nodes': None, 'max_nodes': None}, 'worker': {'instance': None, 'min_nodes': None, 'max_nodes': None}}}, 'google_cloud_platform': {'project': None, 'region': None, 'zone': None, 'availability_zones': [], 'kubernetes_version': None, 'node_groups': {'general': {'instance': None, 'min_nodes': None, 'max_nodes': None}, 'user': {'instance': None, 'min_nodes': None, 'max_nodes': None}, 'worker': {'instance': None, 'min_nodes': None, 'max_nodes': None}}}, 'amazon_web_services': {'region': None, 'availability_zones': [], 'kubernetes_version': None, 'node_groups': {'general': {'instance': None, 'min_nodes': None, 'max_nodes': None}, 'user': {'instance': None, 'min_nodes': None, 'max_nodes': None}, 'worker': {'instance': None, 'min_nodes': None, 'max_nodes': None}}}, '_extensions': ['qhub.render.jinja.YamlifyExtension', 'qhub.render.jinja.JsonifyExtension']})}
```

**Comment by aktech** [comment]
Ok, so the issue is `shared_filesystem` is correctly spelled and the qhub render expects it to be incorrectly spelled:

```diff
 storage:
   conda_store: 20Gi
-  shared_filesystem: 10Gi
+  shared_filesytem: 10Gi
```

**Comment by aktech** [comment]
Ok, so this problem is with the latest released version and not in master, closing this.
