### ISSUE TITLE
[bug] ruamel is not being properly installed in the pip package

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#553]
## Describe the bug
Ruamel isn't properly imported. When running the render command I see this error:
```shell
$ qhub render -c qhub-config.yaml -o ./
Traceback (most recent call last):
  File "/home/tyler/anaconda3/bin/qhub", line 5, in <module>
    from qhub.__main__ import main
  File "/home/tyler/anaconda3/lib/python3.7/site-packages/qhub/__main__.py", line 3, in <module>
    from qhub.cli import cli
  File "/home/tyler/anaconda3/lib/python3.7/site-packages/qhub/cli/__init__.py", line 6, in <module>
    from qhub.cli.deploy import create_deploy_subcommand
  File "/home/tyler/anaconda3/lib/python3.7/site-packages/qhub/cli/deploy.py", line 4, in <module>
    from ruamel import yaml
ModuleNotFoundError: No module named 'ruamel'
```

The package in the setup.py file has a `.yml` extension when it shouldn't:
https://github.com/Quansight/qhub/blob/main/setup.py#L36

**Comment by tylerpotts** [comment]
This was a local environment error that caused the problem. Solved by creating a blank conda environment and pip install qhub again.
