### ISSUE TITLE
Building GPU environments in qhub

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#590]
Right now environments in qhub are built with conda-store. Conda-store has a base image that it uses to build images with. Am running into an issue where system level packages are not available.

For the following environment

```shell
  "environment-gpu-training.yaml":
            name: gpu-training
            channels:
              - conda-forge
            dependencies:
              - python
              - ipykernel
              - ipywidgets
              - python-graphviz
              - dask ==2.30.0
              - distributed ==2.30.1
              - dask-gateway ==0.9.0
              - cudatoolkit
              - numba
              - scikit-image
              - cupy
              - pycuda
              - dask-cuda
              - cutensor
              - napari
```

```shell
ERROR conda.core.link:_execute(700): An error occurred while installing package 'conda-forge::pyopengl-3.1.5-py_0'.
Rolling back transaction: ...working... done

LinkError: post-link script failed for package conda-forge::pyopengl-3.1.5-py_0
location of failed script: /home/conda/store/4c31211ba200b9de8c491629e0c2622403d6e926bb4a67aada117f2b1e6ab75e-gpu-training/bin/.pyopengl-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Warning: Missing OpenGL driver, install with yum install mesa-libGL-devel or equivalent

stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/conda/store/4c31211ba200b9de8c491629e0c2622403d6e926bb4a67aada117f2b1e6ab75e-gpu-training/lib/python3.8/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/home/conda/store/4c31211ba200b9de8c491629e0c2622403d6e926bb4a67aada117f2b1e6ab75e-gpu-training/lib/python3.8/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/home/conda/store/4c31211ba200b9de8c491629e0c2622403d6e926bb4a67aada117f2b1e6ab75e-gpu-training/lib/python3.8/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/home/conda/store/4c31211ba200b9de8c491629e0c2622403d6e926bb4a67aada117f2b1e6ab75e-gpu-training/lib/python3.8/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'
```

**Comment by costrouc** [comment]
Fix is to include the build assumptions of conda in the conda-store image. I can't seem to find the link to assumed packages right now

**Comment by costrouc** [comment]
Okay I can reproduce this issue @aktech 

```
docker run  -it quansight/conda-store:e2051a36e60bd3abd9aa44105f240b359ee6bab7 /bin/bash
```

Create the following environment (seems to happen when pyopengl is installed

```yaml
name: gpu-training-test
channels:
  - conda-forge
dependencies:
  - python
  - ipykernel
  - ipywidgets
  - python-graphviz
  - dask ==2.30.0
  - distributed ==2.30.1
  - dask-gateway ==0.9.0
  - cudatoolkit-dev
  - numba
  - scikit-image
  - cupy
  - pyopengl
```

```shell
conda env create -f environment.yaml
````

```
Downloading and Extracting Packages
pyopengl-3.1.5       | 854 KB    | ########################################################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: / b'By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html\n'
| b''
| b''
| b'Enabling notebook extension jupyter-js-widgets/extension...\n      - Validating: \x1b[32mOK\x1b[0m\n'
done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'conda-forge::pyopengl-3.1.5-py_0'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::pyopengl-3.1.5-py_0
location of failed script: /opt/conda/envs/gpu-training1/bin/.pyopengl-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Warning: Missing OpenGL driver, install with yum install mesa-libGL-devel or equivalent

stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/gpu-training1/lib/python3.8/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/opt/conda/envs/gpu-training1/lib/python3.8/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/opt/conda/envs/gpu-training1/lib/python3.8/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/opt/conda/envs/gpu-training1/lib/python3.8/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'

return code: 1

()
```

**Comment by costrouc** [comment]
Doing https://docs.anaconda.com/anaconda/install/linux/ fixed the issue which is what conda requires in the first place so is a bug with conda-store's default image.

**Comment by costrouc** [comment]
We already do this to the jupyterlab image so we are good on that end https://github.com/Quansight/qhub/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/image/jupyterlab/apt.txt

**Comment by costrouc** [comment]
Actions that need to be done in a PR:
  - create a docker image based on https://github.com/Quansight/qhub/blob/51ed41bd1cc1bb13cb0e3fdb729ef6837c1ffcd3/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/services/conda-store/main.tf#L90 and add the `apt` packages push to docker hub
  - on the qhub side of things add a default image
    - add conda-store as a key https://github.com/Quansight/qhub/blob/51ed41bd1cc1bb13cb0e3fdb729ef6837c1ffcd3/qhub/schema.py#L88 to the schema and all related references (docs, initialize.py, etc.)
    -  the `conda-store` key will now be used in the terraform modules https://github.com/Quansight/qhub/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/services/conda-store/variables.tf and then feed the variable to the main.tf

**Comment by brl0** [comment]
Making these changes would also address #309.

**Comment by costrouc** [comment]
@brl0 this is the exact issue we ran into. Thanks for linking that issue. This should be resolved when this PR is merged and a new release is created.
